import os
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
EMBEDDING_MODEL = "text-embedding-3-small"
LLM_MODEL = "gpt-4.1-2025-04-14"

def embed_text(text):
    """
    Generate an embedding for a given text string.

    Args:
        text (str): The input text to be embedded.
    
    Returns:
        list: The embedding vector for the input text.
    """
    response = client.embeddings.create(
        input=text,
        model=EMBEDDING_MODEL
    )
    return response.data[0].embedding

def get_response_structured(text, structured):
    """
    Generate a response from the LLM based on the input message and structured data.

    Args:
        text (str): The input text for which the LLM should generate a response.
        structured (class): The structured data that the LLM will use as an outline.
    
    Returns:
        str: The output text generated by the LLM.
    """
    response = client.responses.parse(
        input=text,
        model=LLM_MODEL,
        text_format=structured
    )
    
    return response.output_parsed

def get_response(text):
    """
    Generate a response from the LLM based on the input text.

    Args:
        text (str): The input text for which the LLM should generate a response.
    
    Returns:
        str: The output text generated by the LLM.
    """
    response = client.responses.create(
        input=text,
        model=LLM_MODEL
    )

    return response.output_text